### ISSUE TITLE
Modify consumer api to return detailed error responses

### ISSUE THREAD

**Issue by pradyutsarma** [cloudfoundry/noaa#27]
The consumer api currently returns only the message in case of any error that occurs during any of the api calls. Can we modify the api to also return some more detail about the error like the statusCode/errorType for callers who would like a little more information about what went wrong and react appropriately.

**Comment by ahevenor** [comment]
@pradyutsarma thanks for your contribution. I have scheduled this to be reviewed in our next planning meeting.

**Comment by jasonkeene** [comment]
I'm all for more helpful error messages. @pradyutsarma Did you have a specific error that came back that was not helpful? What api were you using?

**Comment by pradyutsarma** [comment]
The containerEnvelopes method as of now, returns just the error message. It would be nice for the API to return some more context information like an ErrCode or the ErrType for clients to react accordingly. For example: detect a connect failure.

**Comment by jasonkeene** [comment]
If you specifically want to know if there was an http error we could return an `error` who's concrete type implements an interface, something like:

```go
type httpError interface {
    StatusCode() int
}
```

You could then have a type switch/assertion in the calling code:

```go
_, err := c.ContainerMetrics()
switch err := err.(type) {
case httpError:
    // do something special with http error
    log.Printf("got http error: %d %s", err.StatusCode(), err)
default:
    log.Printf("got unknown error: %s", err)
}
```

I would prefer specifying tiny interfaces such as this that expose useful information rather than enumerating every error that could possibly be returned and assigning names or codes to them.

In [Dave Cheney's blog post about errors](https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully) he discusses this method as "asserting on behaviour" if you would like to read about it.

I will bring this up with the team for discussion. That said, I would welcome a PR for the above style.

**Comment by ahevenor** [comment]
We are closing this. Feel free to submit a PR for the desired change.
